spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_cloud_2022?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
